package app.molby.rcrecommender.api.rating;

import app.molby.rcrecommender.domain.rating.CoasterRatingEntity;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.ExampleObject;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.responses.ApiResponses;
import io.swagger.v3.oas.annotations.tags.Tag;
import jakarta.validation.Valid;
import lombok.RequiredArgsConstructor;
import org.springframework.http.HttpStatus;
import org.springframework.web.bind.annotation.*;

import java.util.List;

@RestController
@RequestMapping("/ratings")
@RequiredArgsConstructor
@Tag(
        name = "Coaster Ratings",
        description = "CRUD operations for roller coaster ratings used to build user preference profiles " +
                "for personalized coaster recommendations."
)
/**
 * REST controller for managing roller coaster ratings in the
 * roller coaster recommender application.
 *
 * <p>Provides endpoints to create, read, update, and delete user ratings
 * for specific roller coasters. These ratings are consumed by the
 * recommendation engine to infer user preferences.</p>
 */
public class CoasterRatingController {

    private final CoasterRatingService ratingService;
    private final CoasterRatingMapper mapper;

    // ---- CREATE ----

    /**
     * Create a new roller coaster rating.
     *
     * @param dto the rating data submitted by the client
     * @return the persisted rating with an assigned identifier
     */
    @PostMapping
    @ResponseStatus(HttpStatus.CREATED)
    @Operation(
            summary = "Create a new coaster rating",
            description = "Creates a new numeric rating for a specific roller coaster. " +
                    "Each user may rate a given coaster at most once.",
            tags = {"Coaster Ratings"}
    )
    @ApiResponses({
            @ApiResponse(
                    responseCode = "201",
                    description = "Rating created successfully",
                    content = @Content(
                            mediaType = "application/json",
                            schema = @Schema(
                                    implementation = CoasterRatingDto.class,
                                    name = "CoasterRatingCreateResponse",
                                    title = "Created Coaster Rating",
                                    description = "The newly created coaster rating."
                            ),
                            examples = @ExampleObject(
                                    name = "CreatedRating",
                                    summary = "Created rating example",
                                    description = "Example of a newly created rating for a roller coaster.",
                                    value = """
                                        {
                                          "id": 2001,
                                          "userId": "funky_man",
                                          "coasterId": 102,
                                          "rating": 4.5
                                        }
                                        """
                            )
                    )
            ),
            @ApiResponse(
                    responseCode = "400",
                    description = "Validation failed for the provided rating data",
                    content = @Content(
                            mediaType = "application/json",
                            schema = @Schema(
                                    implementation = app.molby.rcrecommender.api.shared.ValidationErrorResponse.class,
                                    name = "CoasterRatingValidationError",
                                    title = "Coaster Rating Validation Error",
                                    description = "Details about validation errors when creating a rating."
                            )
                    )
            )
    })
    public CoasterRatingDto create(
            @io.swagger.v3.oas.annotations.parameters.RequestBody(
                    description = "Rating data to create. The ID is omitted because it is generated by the system.",
                    required = true,
                    content = @Content(
                            mediaType = "application/json",
                            schema = @Schema(
                                    implementation = CoasterRatingDto.class,
                                    name = "CoasterRatingCreateRequest",
                                    title = "Coaster Rating Creation Request",
                                    description = "Payload used to create a new coaster rating."
                            ),
                            examples = @ExampleObject(
                                    name = "CreateRatingRequest",
                                    summary = "Rating creation request example",
                                    description = "Example request body for creating a new coaster rating.",
                                    value = """
                                        {
                                          "id": 44,
                                          "userId": "superman",
                                          "coasterId": 102,
                                          "rating": 4.5
                                        }
                                        """
                            )
                    )
            )
            @RequestBody @Valid CoasterRatingDto coasterRatingDto
    ) {
        CoasterRatingEntity coasterRatingEntity = mapper.toEntity(coasterRatingDto);
        coasterRatingEntity = ratingService.create(coasterRatingEntity);
        return mapper.toDto(coasterRatingEntity);
    }

    /**
     * Retrieve a single coaster rating by its ID.
     *
     * @param id the unique identifier of the rating
     * @return the corresponding {@link CoasterRatingDto}
     */
    @GetMapping("/{id}")
    @Operation(
            summary = "Get rating by ID",
            description = "Retrieves a single coaster rating by its unique identifier.",
            tags = {"Coaster Ratings"}
    )
    @ApiResponses({
            @ApiResponse(
                    responseCode = "200",
                    description = "Rating found",
                    content = @Content(
                            mediaType = "application/json",
                            schema = @Schema(
                                    implementation = CoasterRatingDto.class,
                                    name = "CoasterRatingGetByIdResponse",
                                    title = "Coaster Rating",
                                    description = "Coaster rating that matches the requested ID."
                            ),
                            examples = @ExampleObject(
                                    name = "RatingById",
                                    summary = "Rating by ID example",
                                    description = "Example response for a single coaster rating.",
                                    value = """
                                        {
                                          "id": 2001,
                                          "userId": "george_jetson",
                                          "coasterId": 102,
                                          "rating": 4.5
                                        }
                                        """
                            )
                    )
            ),
            @ApiResponse(
                    responseCode = "404",
                    description = "Rating not found",
                    content = @Content(
                            mediaType = "application/json",
                            schema = @Schema(
                                    implementation = app.molby.rcrecommender.api.shared.ErrorResponse.class,
                                    name = "CoasterRatingNotFoundError",
                                    title = "Coaster Rating Not Found Error",
                                    description = "Error details when the requested rating does not exist."
                            )
                    )
            )
    })
    public CoasterRatingDto findById(
            @Parameter(
                    name = "id",
                    description = "ID of the coaster rating to retrieve.",
                    example = "2001",
                    required = true
            )
            @PathVariable Long id
    ) {
        CoasterRatingEntity coasterRatingEntity = ratingService.getById(id);
        return mapper.toDto(coasterRatingEntity);
    }

    /**
     * Retrieve all coaster ratings.
     *
     * @return list of all {@link CoasterRatingDto} instances
     */
    @GetMapping
    @Operation(
            summary = "List all coaster ratings",
            description = "Returns all coaster ratings currently stored in the system.",
            tags = {"Coaster Ratings"}
    )
    @ApiResponse(
            responseCode = "200",
            description = "List of ratings",
            content = @Content(
                    mediaType = "application/json",
                    schema = @Schema(
                            implementation = CoasterRatingDto.class,
                            name = "CoasterRatingListResponse",
                            title = "Coaster Rating List",
                            description = "List of all coaster ratings."
                    ),
                    examples = @ExampleObject(
                            name = "RatingList",
                            summary = "List of ratings example",
                            description = "Example response with multiple coaster ratings.",
                            value = """
                                [
                                  {
                                    "id": 2001,
                                    "userId": "dr_seuss",
                                    "coasterId": 102,
                                    "rating": 4.5
                                  },
                                  {
                                    "id": 2002,
                                    "userId": "john_glenn",
                                    "coasterId": 102,
                                    "rating": 3.5
                                  }
                                ]
                                """
                    )
            )
    )
    public List<CoasterRatingDto> findAll() {
        return ratingService.getAll().stream()
                .map(mapper::toDto)
                .toList();
    }

    // ---- UPDATE ----

    /**
     * Update an existing coaster rating.
     *
     * @param id  the ID of the rating to update
     * @param dto the new state of the rating
     * @return the updated {@link CoasterRatingDto}
     */
    @PutMapping("/{id}")
    @Operation(
            summary = "Update an existing coaster rating",
            description = "Updates all fields of an existing rating with the provided data.",
            tags = {"Coaster Ratings"}
    )
    @ApiResponses({
            @ApiResponse(
                    responseCode = "200",
                    description = "Rating updated successfully",
                    content = @Content(
                            mediaType = "application/json",
                            schema = @Schema(
                                    implementation = CoasterRatingDto.class,
                                    name = "CoasterRatingUpdateResponse",
                                    title = "Updated Coaster Rating",
                                    description = "The updated coaster rating."
                            ),
                            examples = @ExampleObject(
                                    name = "UpdatedRating",
                                    summary = "Updated rating example",
                                    description = "Example response for an updated coaster rating.",
                                    value = """
                                        {
                                          "id": 2001,
                                          "userId": "barney_ruffle",
                                          "coasterId": 102,
                                          "rating": 4.0
                                        }
                                        """
                            )
                    )
            ),
            @ApiResponse(
                    responseCode = "400",
                    description = "Validation failed for the provided rating data",
                    content = @Content(
                            mediaType = "application/json",
                            schema = @Schema(
                                    implementation = app.molby.rcrecommender.api.shared.ValidationErrorResponse.class,
                                    name = "CoasterRatingUpdateValidationError",
                                    title = "Coaster Rating Update Validation Error",
                                    description = "Details about validation errors when updating a rating."
                            )
                    )
            ),
            @ApiResponse(
                    responseCode = "404",
                    description = "Rating not found",
                    content = @Content(
                            mediaType = "application/json",
                            schema = @Schema(
                                    implementation = app.molby.rcrecommender.api.shared.ErrorResponse.class,
                                    name = "CoasterRatingUpdateNotFoundError",
                                    title = "Coaster Rating Update Not Found Error",
                                    description = "Error details when the rating to update does not exist."
                            )
                    )
            )
    })
    public CoasterRatingDto update(
            @Parameter(
                    name = "id",
                    description = "ID of the rating to update.",
                    example = "2001",
                    required = true
            )
            @PathVariable Long id,
            @io.swagger.v3.oas.annotations.parameters.RequestBody(
                    description = "New state of the coaster rating. The ID in the payload, if present, is ignored.",
                    required = true,
                    content = @Content(
                            mediaType = "application/json",
                            schema = @Schema(
                                    implementation = CoasterRatingDto.class,
                                    name = "CoasterRatingUpdateRequest",
                                    title = "Coaster Rating Update Request",
                                    description = "Payload used to update an existing coaster rating."
                            ),
                            examples = @ExampleObject(
                                    name = "UpdateRatingRequest",
                                    summary = "Rating update request example",
                                    description = "Example request body for updating a coaster rating.",
                                    value = """
                                        {
                                          "id": 23,
                                          "userId": "fred_flinstone",
                                          "coasterId": 102,
                                          "rating": 4.0
                                        }
                                        """
                            )
                    )
            )
            @RequestBody @Valid CoasterRatingDto coasterRatingDto
    ) {
        CoasterRatingEntity coasterRatingEntity = mapper.toEntity(coasterRatingDto);
        coasterRatingEntity = ratingService.update(id, coasterRatingEntity);
        return mapper.toDto(coasterRatingEntity);
    }

    // ---- DELETE ----

    /**
     * Delete an existing coaster rating.
     *
     * @param id the ID of the rating to delete
     */
    @DeleteMapping("/{id}")
    @ResponseStatus(HttpStatus.NO_CONTENT)
    @Operation(
            summary = "Delete a coaster rating",
            description = "Deletes the coaster rating with the given ID.",
            tags = {"Coaster Ratings"}
    )
    @ApiResponses({
            @ApiResponse(
                    responseCode = "204",
                    description = "Rating deleted successfully"
            ),
            @ApiResponse(
                    responseCode = "404",
                    description = "Rating not found",
                    content = @Content(
                            mediaType = "application/json",
                            schema = @Schema(
                                    implementation = app.molby.rcrecommender.api.shared.ErrorResponse.class,
                                    name = "CoasterRatingDeleteNotFoundError",
                                    title = "Coaster Rating Delete Not Found Error",
                                    description = "Error details when the rating to delete does not exist."
                            )
                    )
            )
    })
    public void delete(
            @Parameter(
                    name = "id",
                    description = "ID of the rating to delete.",
                    example = "2001",
                    required = true
            )
            @PathVariable Long id
    ) {
        ratingService.delete(id);
    }
}
