package app.molby.rcrecommender.api.rating;

import app.molby.rcrecommender.domain.rating.CoasterRatingEntity;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.ExampleObject;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.responses.ApiResponses;
import io.swagger.v3.oas.annotations.tags.Tag;
import jakarta.validation.Valid;
import lombok.RequiredArgsConstructor;
import org.springdoc.core.annotations.ParameterObject;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.data.domain.Sort;
import org.springframework.data.web.PageableDefault;
import org.springframework.http.HttpStatus;
import org.springframework.web.bind.annotation.*;

import java.util.List;

@RestController
@RequestMapping("/ratings")
@RequiredArgsConstructor
@Tag(
        name = "Coaster Ratings",
        description = "CRUD operations for roller coaster ratings used to build user preference profiles " +
                "for personalized coaster recommendations."
)
/**
 * REST controller for managing roller coaster ratings in the
 * roller coaster recommender application.
 *
 * <p>Provides endpoints to create, read, update, and delete user ratings
 * for specific roller coasters. These ratings are consumed by the
 * recommendation engine to infer user preferences.</p>
 */
public class CoasterRatingController {

    private final CoasterRatingService ratingService;
    private final CoasterRatingMapper mapper;

    // ---- CREATE ----

    /**
     * Create a new roller coaster rating.
     *
     * @param coasterRatingDto the rating data submitted by the client
     * @return the persisted rating with an assigned identifier
     */
    @PostMapping
    @ResponseStatus(HttpStatus.CREATED)
    @Operation(
            summary = "Create a new coaster rating",
            description = "Creates a new numeric rating for a specific roller coaster. " +
                    "Each user may rate a given coaster at most once.",
            tags = {"Coaster Ratings"}
    )
    @ApiResponses({
            @ApiResponse(
                    responseCode = "201",
                    description = "Rating created successfully",
                    content = @Content(
                            mediaType = "application/json",
                            schema = @Schema(
                                    implementation = CoasterRatingDto.class,
                                    name = "CoasterRatingCreateResponse",
                                    title = "Created Coaster Rating",
                                    description = "The newly created coaster rating."
                            ),
                            examples = @ExampleObject(
                                    name = "CreatedRating",
                                    summary = "Created rating example",
                                    description = "Example of a newly created rating for a roller coaster.",
                                    value = """
                                        {
                                          "id": 2001,
                                          "userId": "funky_man",
                                          "coasterId": 102,
                                          "rating": 4.5
                                        }
                                        """
                            )
                    )
            ),
            @ApiResponse(
                    responseCode = "400",
                    description = "Validation failed for the provided rating data",
                    content = @Content(
                            mediaType = "application/json",
                            schema = @Schema(
                                    implementation = app.molby.rcrecommender.api.shared.ValidationErrorResponse.class,
                                    name = "CoasterRatingValidationError",
                                    title = "Coaster Rating Validation Error",
                                    description = "Details about validation errors when creating a rating."
                            )
                    )
            )
    })
    public CoasterRatingDto create(
            @io.swagger.v3.oas.annotations.parameters.RequestBody(
                    description = "Rating data to create. The ID is omitted because it is generated by the system.",
                    required = true,
                    content = @Content(
                            mediaType = "application/json",
                            schema = @Schema(
                                    implementation = CoasterRatingDto.class,
                                    name = "CoasterRatingCreateRequest",
                                    title = "Coaster Rating Creation Request",
                                    description = "Payload used to create a new coaster rating."
                            ),
                            examples = @ExampleObject(
                                    name = "CreateRatingRequest",
                                    summary = "Rating creation request example",
                                    description = "Example request body for creating a new coaster rating.",
                                    value = """
                                        {
                                          "id": 44,
                                          "userId": "superman",
                                          "coasterId": 102,
                                          "rating": 4.5
                                        }
                                        """
                            )
                    )
            )
            @RequestBody @Valid CoasterRatingDto coasterRatingDto
    ) {
        CoasterRatingEntity coasterRatingEntity = mapper.toEntity(coasterRatingDto);
        coasterRatingEntity = ratingService.create(coasterRatingEntity);
        return mapper.toDto(coasterRatingEntity);
    }

    /**
     * Retrieve a single coaster rating by its ID.
     *
     * @param id the unique identifier of the rating
     * @return the corresponding {@link CoasterRatingDto}
     */
    @GetMapping("/{id}")
    @Operation(
            summary = "Get rating by ID",
            description = "Retrieves a single coaster rating by its unique identifier.",
            tags = {"Coaster Ratings"}
    )
    @ApiResponses({
            @ApiResponse(
                    responseCode = "200",
                    description = "Rating found",
                    content = @Content(
                            mediaType = "application/json",
                            schema = @Schema(
                                    implementation = CoasterRatingDto.class,
                                    name = "CoasterRatingGetByIdResponse",
                                    title = "Coaster Rating",
                                    description = "Coaster rating that matches the requested ID."
                            ),
                            examples = @ExampleObject(
                                    name = "RatingById",
                                    summary = "Rating by ID example",
                                    description = "Example response for a single coaster rating.",
                                    value = """
                                        {
                                          "id": 2001,
                                          "userId": "george_jetson",
                                          "coasterId": 102,
                                          "rating": 4.5
                                        }
                                        """
                            )
                    )
            ),
            @ApiResponse(
                    responseCode = "404",
                    description = "Rating not found",
                    content = @Content(
                            mediaType = "application/json",
                            schema = @Schema(
                                    implementation = app.molby.rcrecommender.api.shared.ErrorResponse.class,
                                    name = "CoasterRatingNotFoundError",
                                    title = "Coaster Rating Not Found Error",
                                    description = "Error details when the requested rating does not exist."
                            )
                    )
            )
    })
    public CoasterRatingDto findById(
            @Parameter(
                    name = "id",
                    description = "ID of the coaster rating to retrieve.",
                    example = "2001",
                    required = true
            )
            @PathVariable Long id
    ) {
        CoasterRatingEntity coasterRatingEntity = ratingService.findById(id);
        return mapper.toDto(coasterRatingEntity);
    }


    /**
     * Retrieves a paginated list of coaster ratings.
     *
     * <p>Supports standard Spring Data pagination and sorting parameters:
     * <ul>
     *   <li><code>page</code> - zero-based page index (default: 0)</li>
     *   <li><code>size</code> - page size (default: 20, capped at 100)</li>
     *   <li><code>sort</code> - sorting criteria in the format <code>property,(asc|desc)</code>.
     *       Multiple sort parameters are supported, e.g. <code>sort=rating,desc&sort=id,asc</code>.</li>
     * </ul>
     *
     * @param pageable pagination and sorting information populated from query parameters
     * @return a page of {@link CoasterRatingDto} objects and associated pagination metadata
     */
    @GetMapping
    @Operation(
            summary = "List coaster ratings (paginated)",
            description = """
                Returns a paginated list of coaster ratings currently stored in the system.

                Use the standard Spring Data pagination and sorting query parameters:
                - page: zero-based page index (e.g., 0)
                - size: page size (e.g., 20)
                - sort: property and direction (e.g., sort=rating,desc)
                """,
            tags = {"Coaster Ratings"}
    )
    @ApiResponses({
            @ApiResponse(
                    responseCode = "200",
                    description = "Paginated list of coaster ratings.",
                    content = @Content(
                            mediaType = "application/json",
                            schema = @Schema(
                                    name = "CoasterRatingPageResponse",
                                    title = "Coaster Rating Page",
                                    description = "Paginated response containing coaster ratings and pagination metadata."
                            ),
                            examples = @ExampleObject(
                                    name = "RatingPage",
                                    summary = "Paginated list of ratings example",
                                    description = """
                                        Example response showing a single page of coaster ratings.
                                        Default page size is 20 and the maximum page size is 100.
                                        """,
                                    value = """
                                        {
                                          "content": [
                                            {
                                              "id": 2001,
                                              "userId": "dr_seuss",
                                              "coasterId": 102,
                                              "rating": 4.5
                                            },
                                            {
                                              "id": 2002,
                                              "userId": "john_glenn",
                                              "coasterId": 102,
                                              "rating": 3.5
                                            }
                                          ],
                                          "pageable": {
                                            "pageNumber": 0,
                                            "pageSize": 2,
                                            "sort": {
                                              "sorted": true,
                                              "unsorted": false,
                                              "empty": false
                                            },
                                            "offset": 0,
                                            "paged": true,
                                            "unpaged": false
                                          },
                                          "totalElements": 42,
                                          "totalPages": 21,
                                          "last": false,
                                          "size": 2,
                                          "number": 0,
                                          "sort": {
                                            "sorted": true,
                                            "unsorted": false,
                                            "empty": false
                                          },
                                          "numberOfElements": 2,
                                          "first": true,
                                          "empty": false
                                        }
                                        """
                            )
                    )
            )
    })
    public Page<CoasterRatingDto> findAll(
            @ParameterObject
            @PageableDefault(
                    size = 20,
                    page = 0,
                    sort = "id",
                    direction = Sort.Direction.ASC
            )
            Pageable pageable
    ) {
        return ratingService.findAll(pageable).map(mapper::toDto);
    }

    /**
     * Update an existing coaster rating.
     *
     * @param id  the ID of the rating to update
     * @param coasterRatingDto the new state of the rating
     * @return the updated {@link CoasterRatingDto}
     */
    @PutMapping("/{id}")
    @Operation(
            summary = "Update an existing coaster rating",
            description = "Updates all fields of an existing rating with the provided data.",
            tags = {"Coaster Ratings"}
    )
    @ApiResponses({
            @ApiResponse(
                    responseCode = "200",
                    description = "Rating updated successfully",
                    content = @Content(
                            mediaType = "application/json",
                            schema = @Schema(
                                    implementation = CoasterRatingDto.class,
                                    name = "CoasterRatingUpdateResponse",
                                    title = "Updated Coaster Rating",
                                    description = "The updated coaster rating."
                            ),
                            examples = @ExampleObject(
                                    name = "UpdatedRating",
                                    summary = "Updated rating example",
                                    description = "Example response for an updated coaster rating.",
                                    value = """
                                        {
                                          "id": 2001,
                                          "userId": "barney_ruffle",
                                          "coasterId": 102,
                                          "rating": 4.0
                                        }
                                        """
                            )
                    )
            ),
            @ApiResponse(
                    responseCode = "400",
                    description = "Validation failed for the provided rating data",
                    content = @Content(
                            mediaType = "application/json",
                            schema = @Schema(
                                    implementation = app.molby.rcrecommender.api.shared.ValidationErrorResponse.class,
                                    name = "CoasterRatingUpdateValidationError",
                                    title = "Coaster Rating Update Validation Error",
                                    description = "Details about validation errors when updating a rating."
                            )
                    )
            ),
            @ApiResponse(
                    responseCode = "404",
                    description = "Rating not found",
                    content = @Content(
                            mediaType = "application/json",
                            schema = @Schema(
                                    implementation = app.molby.rcrecommender.api.shared.ErrorResponse.class,
                                    name = "CoasterRatingUpdateNotFoundError",
                                    title = "Coaster Rating Update Not Found Error",
                                    description = "Error details when the rating to update does not exist."
                            )
                    )
            )
    })
    public CoasterRatingDto update(
            @Parameter(
                    name = "id",
                    description = "ID of the rating to update.",
                    example = "2001",
                    required = true
            )
            @PathVariable Long id,
            @io.swagger.v3.oas.annotations.parameters.RequestBody(
                    description = "New state of the coaster rating. The ID in the payload, if present, is ignored.",
                    required = true,
                    content = @Content(
                            mediaType = "application/json",
                            schema = @Schema(
                                    implementation = CoasterRatingDto.class,
                                    name = "CoasterRatingUpdateRequest",
                                    title = "Coaster Rating Update Request",
                                    description = "Payload used to update an existing coaster rating."
                            ),
                            examples = @ExampleObject(
                                    name = "UpdateRatingRequest",
                                    summary = "Rating update request example",
                                    description = "Example request body for updating a coaster rating.",
                                    value = """
                                        {
                                          "id": 23,
                                          "userId": "fred_flinstone",
                                          "coasterId": 102,
                                          "rating": 4.0
                                        }
                                        """
                            )
                    )
            )
            @RequestBody @Valid CoasterRatingDto coasterRatingDto
    ) {
        CoasterRatingEntity coasterRatingEntity = mapper.toEntity(coasterRatingDto);
        coasterRatingEntity = ratingService.update(id, coasterRatingEntity);
        return mapper.toDto(coasterRatingEntity);
    }

    // ---- DELETE ----

    /**
     * Delete an existing coaster rating.
     *
     * @param id the ID of the rating to delete
     */
    @DeleteMapping("/{id}")
    @ResponseStatus(HttpStatus.NO_CONTENT)
    @Operation(
            summary = "Delete a coaster rating",
            description = "Deletes the coaster rating with the given ID.",
            tags = {"Coaster Ratings"}
    )
    @ApiResponses({
            @ApiResponse(
                    responseCode = "204",
                    description = "Rating deleted successfully"
            ),
            @ApiResponse(
                    responseCode = "404",
                    description = "Rating not found",
                    content = @Content(
                            mediaType = "application/json",
                            schema = @Schema(
                                    implementation = app.molby.rcrecommender.api.shared.ErrorResponse.class,
                                    name = "CoasterRatingDeleteNotFoundError",
                                    title = "Coaster Rating Delete Not Found Error",
                                    description = "Error details when the rating to delete does not exist."
                            )
                    )
            )
    })
    public void delete(
            @Parameter(
                    name = "id",
                    description = "ID of the rating to delete.",
                    example = "2001",
                    required = true
            )
            @PathVariable Long id
    ) {
        ratingService.delete(id);
    }
}
