package app.molby.rcrecommender.api.country;

import app.molby.rcrecommender.domain.country.CountryAccessEntity;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.ExampleObject;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.responses.ApiResponses;
import io.swagger.v3.oas.annotations.tags.Tag;
import jakarta.validation.Valid;
import lombok.RequiredArgsConstructor;
import org.springframework.http.HttpStatus;
import org.springframework.web.bind.annotation.*;

import java.util.List;

@RestController
@RequestMapping("/country-access")
@RequiredArgsConstructor
@Tag(
        name = "Country Access",
        description = "CRUD operations for mapping accessible countries between each other, " +
                "used for cross-border coaster trip planning and recommendations."
)
/**
 * REST controller for managing country access mappings in the
 * roller coaster recommender application.
 *
 * <p>Country access mappings define which countries are considered accessible
 * from a given source country. These are used by recommendation logic to
 * determine multi-country coaster trip feasibility.</p>
 */
public class CountryAccessController {

    private final CountryAccessService service;
    private final CountryAccessMapper mapper;

    /**
     * Create a new country access mapping.
     *
     * @param dto the country access DTO containing source and accessible countries
     * @return the persisted {@link CountryAccessDto} with an assigned identifier
     */
    @PostMapping
    @ResponseStatus(HttpStatus.CREATED)
    @Operation(
            summary = "Create a new country access mapping",
            description = "Creates a new directional mapping indicating that coasters in one country " +
                    "should be considered accessible when planning trips from another country.",
            tags = {"Country Access"}
    )
    @ApiResponses({
            @ApiResponse(
                    responseCode = "201",
                    description = "Country access mapping created successfully",
                    content = @Content(
                            mediaType = "application/json",
                            schema = @Schema(
                                    implementation = CountryAccessDto.class,
                                    name = "CountryAccessCreateResponse",
                                    title = "Country Access Mapping Response",
                                    description = "The newly created country access mapping."
                            ),
                            examples = @ExampleObject(
                                    name = "CreatedCountryAccess",
                                    summary = "Created mapping example",
                                    description = "Example of a newly created country access mapping.",
                                    value = """
                                        {
                                          "id": 10,
                                          "sourceCountry": {
                                            "countryName": "United States"
                                          },
                                          "accessibleCountry": {
                                            "countryName": "Canada"
                                          }
                                        }
                                        """
                            )
                    )
            ),
            @ApiResponse(
                    responseCode = "400",
                    description = "Validation failed for the provided mapping data",
                    content = @Content(
                            mediaType = "application/json",
                            schema = @Schema(
                                    implementation = app.molby.rcrecommender.api.shared.ValidationErrorResponse.class,
                                    name = "CountryAccessValidationError",
                                    title = "Country Access Validation Error",
                                    description = "Details about validation errors when creating a country access mapping."
                            )
                    )
            )
    })
    public CountryAccessDto create(
            @io.swagger.v3.oas.annotations.parameters.RequestBody(
                    description = "Country access mapping to create. The ID is omitted because it is generated by the system.",
                    required = true,
                    content = @Content(
                            mediaType = "application/json",
                            schema = @Schema(
                                    implementation = CountryAccessDto.class,
                                    name = "CountryAccessCreateRequest",
                                    title = "Country Access Creation Request",
                                    description = "Payload used to create a new country access mapping."
                            ),
                            examples = @ExampleObject(
                                    name = "CreateCountryAccessRequest",
                                    summary = "Country access creation request example",
                                    description = "Example request body for creating a country access mapping.",
                                    value = """
                                        {
                                          "sourceCountry": {
                                            "countryName": "United States"
                                          },
                                          "accessibleCountry": {
                                            "countryName": "Canada"
                                          }
                                        }
                                        """
                            )
                    )
            )
            @RequestBody @Valid CountryAccessDto countryAccessDto
    ) {
        CountryAccessEntity countryAccessEntity = mapper.toCountryAccessEntity(countryAccessDto);
        countryAccessEntity = service.create(countryAccessEntity);
        return mapper.toCountryAccessDto(countryAccessEntity);
    }

    /**
     * Retrieve a single country access mapping by its ID.
     *
     * @param id the unique identifier of the country access mapping
     * @return the {@link CountryAccessDto} matching the given ID
     */
    @GetMapping("/{id}")
    @Operation(
            summary = "Get country access mapping by ID",
            description = "Retrieves a single country access mapping by its unique identifier.",
            tags = {"Country Access"}
    )
    @ApiResponses({
            @ApiResponse(
                    responseCode = "200",
                    description = "Mapping found",
                    content = @Content(
                            mediaType = "application/json",
                            schema = @Schema(
                                    implementation = CountryAccessDto.class,
                                    name = "CountryAccessGetByIdResponse",
                                    title = "Country Access Mapping Response",
                                    description = "Country access mapping that matches the requested ID."
                            ),
                            examples = @ExampleObject(
                                    name = "CountryAccessById",
                                    summary = "Mapping by ID example",
                                    description = "Example response for a single country access mapping.",
                                    value = """
                                        {
                                          "id": 10,
                                          "sourceCountry": {
                                            "countryName": "United States"
                                          },
                                          "accessibleCountry": {
                                            "countryName": "Canada"
                                          }
                                        }
                                        """
                            )
                    )
            ),
            @ApiResponse(
                    responseCode = "404",
                    description = "Mapping not found",
                    content = @Content(
                            mediaType = "application/json",
                            schema = @Schema(
                                    implementation = app.molby.rcrecommender.api.shared.ErrorResponse.class,
                                    name = "CountryAccessNotFoundError",
                                    title = "Country Access Not Found Error",
                                    description = "Error details when the requested country access mapping is not found."
                            )
                    )
            )
    })
    public CountryAccessDto findById(
            @Parameter(
                    name = "id",
                    description = "ID of the country access mapping to retrieve.",
                    example = "10",
                    required = true
            )
            @PathVariable Long id
    ) {
        CountryAccessEntity entity = service.getById(id);
        return mapper.toCountryAccessDto(entity);
    }

    /**
     * Retrieve all country access mappings.
     *
     * @return list of all {@link CountryAccessDto} mappings
     */
    @GetMapping
    @Operation(
            summary = "List all country access mappings",
            description = "Returns all configured country access mappings used for trip planning.",
            tags = {"Country Access"}
    )
    @ApiResponse(
            responseCode = "200",
            description = "List of mappings",
            content = @Content(
                    mediaType = "application/json",
                    schema = @Schema(
                            implementation = CountryAccessDto.class,
                            name = "CountryAccessListResponse",
                            title = "Country Access Mapping List",
                            description = "List of all country access mappings."
                    ),
                    examples = @ExampleObject(
                            name = "CountryAccessList",
                            summary = "List of mappings example",
                            description = "Example response with multiple country access mappings.",
                            value = """
                                [
                                  {
                                    "id": 10,
                                    "sourceCountry": {
                                      "countryName": "United States"
                                    },
                                    "accessibleCountry": {
                                      "countryName": "Canada"
                                    }
                                  },
                                  {
                                    "id": 11,
                                    "sourceCountry": {
                                      "countryName": "United States"
                                    },
                                    "accessibleCountry": {
                                      "countryName": "Mexico"
                                    }
                                  }
                                ]
                                """
                    )
            )
    )
    public List<CountryAccessDto> findAll() {
        return service.getAll().stream()
                .map(mapper::toCountryAccessDto)
                .toList();
    }

    /**
     * Update an existing country access mapping.
     *
     * @param id  the ID of the mapping to update
     * @param countryAccessDto the new state of the country access mapping
     * @return the updated {@link CountryAccessDto}
     */
    @PutMapping("/{id}")
    @Operation(
            summary = "Update an existing country access mapping",
            description = "Updates an existing country access mapping with the provided source and accessible countries.",
            tags = {"Country Access"}
    )
    @ApiResponses({
            @ApiResponse(
                    responseCode = "200",
                    description = "Mapping updated successfully",
                    content = @Content(
                            mediaType = "application/json",
                            schema = @Schema(
                                    implementation = CountryAccessDto.class,
                                    name = "CountryAccessUpdateResponse",
                                    title = "Updated Country Access Mapping",
                                    description = "The updated country access mapping."
                            ),
                            examples = @ExampleObject(
                                    name = "UpdatedCountryAccess",
                                    summary = "Updated mapping example",
                                    description = "Example response for an updated country access mapping.",
                                    value = """
                                        {
                                          "id": 10,
                                          "sourceCountry": {
                                            "countryName": "United States"
                                          },
                                          "accessibleCountry": {
                                            "countryName": "Canada"
                                          }
                                        }
                                        """
                            )
                    )
            ),
            @ApiResponse(
                    responseCode = "400",
                    description = "Validation failed for the provided mapping data",
                    content = @Content(
                            mediaType = "application/json",
                            schema = @Schema(
                                    implementation = app.molby.rcrecommender.api.shared.ValidationErrorResponse.class,
                                    name = "CountryAccessUpdateValidationError",
                                    title = "Country Access Update Validation Error",
                                    description = "Details about validation errors when updating a country access mapping."
                            )
                    )
            ),
            @ApiResponse(
                    responseCode = "404",
                    description = "Mapping not found",
                    content = @Content(
                            mediaType = "application/json",
                            schema = @Schema(
                                    implementation = app.molby.rcrecommender.api.shared.ErrorResponse.class,
                                    name = "CountryAccessUpdateNotFoundError",
                                    title = "Country Access Update Not Found Error",
                                    description = "Error details when the country access mapping to update does not exist."
                            )
                    )
            )
    })
    public CountryAccessDto update(
            @Parameter(
                    name = "id",
                    description = "ID of the country access mapping to update.",
                    example = "10",
                    required = true
            )
            @PathVariable Long id,
            @io.swagger.v3.oas.annotations.parameters.RequestBody(
                    description = "New state of the country access mapping. The ID in the payload, if present, is ignored.",
                    required = true,
                    content = @Content(
                            mediaType = "application/json",
                            schema = @Schema(
                                    implementation = CountryAccessDto.class,
                                    name = "CountryAccessUpdateRequest",
                                    title = "Country Access Update Request",
                                    description = "Payload used to update an existing country access mapping."
                            ),
                            examples = @ExampleObject(
                                    name = "UpdateCountryAccessRequest",
                                    summary = "Country access update request example",
                                    description = "Example request body for updating an existing country access mapping.",
                                    value = """
                                        {
                                          "sourceCountry": {
                                            "countryName": "United States"
                                          },
                                          "accessibleCountry": {
                                            "countryName": "Canada"
                                          }
                                        }
                                        """
                            )
                    )
            )
            @RequestBody @Valid CountryAccessDto countryAccessDto
    ) {
        CountryAccessEntity countryAccessEntity = mapper.toCountryAccessEntity(countryAccessDto);
        countryAccessEntity = service.update(id, countryAccessEntity);
        return mapper.toCountryAccessDto(countryAccessEntity);
    }

    /**
     * Delete an existing country access mapping.
     *
     * @param id the ID of the mapping to delete
     */
    @DeleteMapping("/{id}")
    @ResponseStatus(HttpStatus.NO_CONTENT)
    @Operation(
            summary = "Delete a country access mapping",
            description = "Deletes the country access mapping with the given ID.",
            tags = {"Country Access"}
    )
    @ApiResponses({
            @ApiResponse(
                    responseCode = "204",
                    description = "Mapping deleted successfully"
            ),
            @ApiResponse(
                    responseCode = "404",
                    description = "Mapping not found",
                    content = @Content(
                            mediaType = "application/json",
                            schema = @Schema(
                                    implementation = app.molby.rcrecommender.api.shared.ErrorResponse.class,
                                    name = "CountryAccessDeleteNotFoundError",
                                    title = "Country Access Delete Not Found Error",
                                    description = "Error details when the country access mapping to delete does not exist."
                            )
                    )
            )
    })
    public void delete(
            @Parameter(
                    name = "id",
                    description = "ID of the country access mapping to delete.",
                    example = "10",
                    required = true
            )
            @PathVariable Long id
    ) {
        service.delete(id);
    }
}
